# Generated by Django 6.0.3 on 2026-03-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('DBA', 'Department of Business Administration'), ('CSE', 'Department of Computer Science and Engineering'), ('CE', 'Department of Civil Engineering'), ('EEE', 'Department of Electrical and Electronic Engineering'), ('Pharmacy', 'Department of Pharmacy'), ('Law', 'Department of Law and Human Rights'), ('English', 'Department of English'), ('Architecture', 'Department of Architecture')], max_length=100, null=True),
        ),
    ]
