# Generated by Django 6.0.3 on 2026-04-30 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=20)),
                ('department', models.CharField(choices=[('DBA', 'Department of Business Administration (DBA)'), ('CSE', 'Department of Computer Science and Engineering (CSE)'), ('CE', 'Department of Civil Engineering (CE)'), ('EEE', 'Department of Electrical and Electronic Engineering (EEE)'), ('Pharmacy', 'Department of Pharmacy'), ('Law', 'Department of Law and Human Rights'), ('English', 'Department of English'), ('Architecture', 'Department of Architecture')], max_length=100)),
                ('description', models.TextField()),
                ('place', models.CharField(choices=[('Faculty Office', 'Faculty Office'), ('HOD Office', 'HOD Office'), ('Meeting Room A', 'Meeting Room A'), ('Meeting Room B', 'Meeting Room B'), ('Online (Zoom/Meet)', 'Online (Zoom/Meet)')], max_length=100)),
                ('preferred_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['-created_at'],
            },
        ),
    ]
