# Generated by Django 6.0.3 on 2026-04-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_with',
            field=models.CharField(choices=[('Harassment Committee', 'Harassment Committee'), ('Proctorial Committee', 'Proctorial Committee')], default='Harassment Committee', max_length=50),
        ),
    ]
