# Generated by Django 6.0.3 on 2026-05-01 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='place',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='preferred_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='incident_type',
            field=models.CharField(choices=[('Harassment', 'Harassment'), ('Discrimination', 'Discrimination'), ('Abuse', 'Abuse'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
