# Generated by Django 6.0.3 on 2026-05-10 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='committee_type',
            field=models.CharField(blank=True, choices=[('Harassment Committee', 'Harassment Committee'), ('Proctorial Committee', 'Proctorial Committee')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Forwarded to Committee', 'Forwarded to Committee'), ('Meeting Scheduled', 'Meeting Scheduled'), ('Rejected by Committee', 'Rejected by Committee'), ('Closed', 'Closed')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Faculty', 'Faculty'), ('HOD', 'Head of Department'), ('Staff', 'Staff'), ('Admin', 'Administrator'), ('Committee', 'Committee Member')], max_length=20),
        ),
        migrations.CreateModel(
            name='AppointmentUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('meeting_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Forwarded to Committee', 'Forwarded to Committee'), ('Meeting Scheduled', 'Meeting Scheduled'), ('Rejected by Committee', 'Rejected by Committee'), ('Closed', 'Closed')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='users.appointment')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
