# Generated by Django 6.0.5 on 2026-05-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_committee_type_alter_appointment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Faculty', 'Faculty'), ('HOD', 'Head of Department'), ('Staff', 'Staff'), ('DAO', 'Dean of Administration Office'), ('Admin', 'Administrator'), ('Committee', 'Committee Member')], max_length=20),
        ),
    ]
