# Generated by Django 6.0.3 on 2026-05-18 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0012_clarificationrequest_target_user_and_more'),
        ('users', '0013_alter_appointment_id_alter_appointmentupdate_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='converted_to_complaint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_appointment', to='complaints.complaint'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='meeting_location',
            field=models.CharField(blank=True, help_text='e.g. Room 204, Admin Block / Google Meet link', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='outcome',
            field=models.CharField(choices=[('Pending', 'Pending — No outcome yet'), ('Resolved Informally', 'Resolved Informally — Case closed'), ('Needs Formal Action', 'Needs Formal Action — Student should file complaint')], default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='incident_type',
            field=models.CharField(choices=[('Harassment', 'Harassment'), ('Bullying', 'Bullying'), ('Discrimination', 'Discrimination'), ('Faculty Misconduct', 'Faculty Misconduct'), ('Mental Pressure', 'Mental Pressure'), ('Abuse', 'Abuse'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Forwarded to Committee', 'Forwarded to Committee'), ('Meeting Scheduled', 'Meeting Scheduled'), ('Rejected by Committee', 'Rejected by Committee'), ('Resolved Informally', 'Resolved Informally'), ('Needs Formal Action', 'Needs Formal Action'), ('Closed', 'Closed')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointmentupdate',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Forwarded to Committee', 'Forwarded to Committee'), ('Meeting Scheduled', 'Meeting Scheduled'), ('Rejected by Committee', 'Rejected by Committee'), ('Resolved Informally', 'Resolved Informally'), ('Needs Formal Action', 'Needs Formal Action'), ('Closed', 'Closed')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='AppointmentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_notes', to=settings.AUTH_USER_MODEL)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='users.appointment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
