# Generated by Django 6.0.3 on 2026-05-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_appointment_converted_to_complaint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='type',
            field=models.CharField(choices=[('Appointment', 'Appointment'), ('Direct Complaint', 'Direct Complaint')], default='Appointment', max_length=20),
        ),
    ]
