# Generated by Django 6.0.4 on 2026-04-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_alter_course_id_alter_courseassignment_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='class_section',
            field=models.CharField(blank=True, choices=[('A', 'Section A'), ('B', 'Section B'), ('C', 'Section C'), ('D', 'Section D')], help_text='Assign faculty for a specific section', max_length=1, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='courseassignment',
            unique_together={('course', 'class_section')},
        ),
    ]
