# Generated by Django 5.2.7 on 2026-05-14 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_alter_course_id_alter_courseassignment_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Spring 2026 Mid-Term', max_length=100)),
                ('semester', models.CharField(help_text='e.g. Spring 2026', max_length=50)),
                ('period_type', models.CharField(choices=[('Mid-Term', 'Mid-Term Feedback'), ('End-Term', 'End-Term Feedback'), ('Special', 'Special Feedback Round')], default='Mid-Term', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Feedback Period',
                'verbose_name_plural': 'Feedback Periods',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='attendance_percentage',
            field=models.FloatField(default=100.0, help_text='Student attendance percentage (0-100)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='courseassignment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='courseregistration',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='feedbackresponse',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_period',
            field=models.ForeignKey(blank=True, help_text='The feedback period/round this was submitted during', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='feedback.feedbackperiod'),
        ),
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('student', 'course', 'feedback_period')},
        ),
    ]
