# Generated by Django 6.0.3 on 2026-05-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0008_feedbackperiod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseassignment',
            name='class_section',
            field=models.CharField(blank=True, help_text='Assign faculty for a specific section (e.g. A, B, Lab 1)', max_length=50, null=True),
        ),
    ]
