# Generated by Django 6.0.3 on 2026-05-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0009_alter_courseassignment_class_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseassignment',
            name='class_section',
            field=models.CharField(blank=True, choices=[('A', 'Section A'), ('B', 'Section B'), ('C', 'Section C'), ('D', 'Section D')], help_text='Assign faculty for a specific section', max_length=1, null=True),
        ),
    ]
