# Generated by Django 6.0.3 on 2026-05-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0010_alter_courseassignment_class_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseregistration',
            name='is_dropped',
            field=models.BooleanField(default=False, help_text='Student manually dropped this course'),
        ),
    ]
