# Generated by Django 6.0.5 on 2026-05-16 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0011_courseregistration_is_dropped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseregistration',
            name='is_dropped',
        ),
    ]
