# Generated by Django 6.0.3 on 2026-05-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0012_remove_courseregistration_is_dropped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackperiod',
            name='period_type',
            field=models.CharField(choices=[('Mid-Term', 'Mid-Term Feedback'), ('Final-Term', 'Final-Term Feedback'), ('Special', 'Special Feedback Round')], default='Mid-Term', max_length=20),
        ),
    ]
