# Generated by Django 6.0.3 on 2026-05-21 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0013_alter_feedbackperiod_period_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together=set(),
        ),
    ]
