# Generated by Django 6.0.3 on 2026-05-21 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0014_remove_feedback_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackperiod',
            name='period_type',
        ),
    ]
