# Generated by Django 6.0.3 on 2026-05-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0015_remove_period_type_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackperiod',
            name='period_type',
            field=models.CharField(choices=[('Mid-Term', 'Mid-Term Feedback')], default='Mid-Term', max_length=20),
        ),
    ]
