# Generated by Django 6.0.3 on 2026-05-21 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0016_add_period_type_midterm_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackperiod',
            name='end_date',
        ),
    ]
