# Generated by Django 6.0.3 on 2026-05-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0017_remove_end_date_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseregistration',
            name='class_section',
            field=models.CharField(blank=True, choices=[('A', 'Section A'), ('B', 'Section B'), ('C', 'Section C'), ('D', 'Section D')], help_text='Section the student belongs to in this course', max_length=1, null=True),
        ),
    ]
