# Generated by Django 6.0.3 on 2026-04-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_alter_complaint_id_alter_complaintupdate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_type',
            field=models.CharField(choices=[('Faculty', 'Complaint about Faculty'), ('HOD', 'Complaint about HOD'), ('Staff', 'Complaint about Staff'), ('Facility', 'Facility Issue')], max_length=20),
        ),
    ]
