# Generated by Django 6.0.3 on 2026-05-08 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_alter_complaint_complaint_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaintupdate',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='complaint',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='ComplaintInvestigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigations_assigned_by', to=settings.AUTH_USER_MODEL)),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investigation', to='complaints.complaint')),
                ('investigators', models.ManyToManyField(limit_choices_to={'role__in': ['Faculty', 'HOD']}, related_name='investigations_assigned_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestigationFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(choices=[('Complaint Valid', 'Complaint is Valid'), ('Complaint Invalid', 'Complaint is Invalid'), ('Partially Valid', 'Partially Valid'), ('Needs Further Review', 'Needs Further Review')], max_length=30)),
                ('findings', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='complaints.complaintinvestigation')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigation_findings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('investigation', 'submitted_by')},
            },
        ),
    ]
