# Generated by Django 6.0.3 on 2026-05-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_alter_complaintupdate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='final_action_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Review'), ('Under Investigation', 'Under Investigation'), ('Findings Submitted', 'Findings Submitted'), ('Resolved', 'Resolved'), ('Escalated', 'Escalated to Higher Authority')], default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='investigationfinding',
            name='verdict',
            field=models.CharField(choices=[('Proven', 'Complaint is Proven'), ('Unproven', 'Complaint is Unproven'), ('Needs More Info', 'Needs More Info')], max_length=30),
        ),
    ]
