# Generated by Django 5.2.7 on 2026-05-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0009_alter_complaint_id_alter_complaintinvestigation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='resolution_deadline',
            field=models.DateField(blank=True, help_text='Deadline for resolving this complaint', null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_type',
            field=models.CharField(choices=[('Faculty', 'Complaint about Faculty'), ('HOD', 'Complaint about HOD'), ('Staff', 'Complaint about Staff'), ('Facility', 'Facility Issue'), ('Advice', 'General Advice'), ('Opinion', 'Opinion/Suggestion')], max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='complaintinvestigation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='complaintupdate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='investigationfinding',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
