# Generated by Django 6.0.3 on 2026-05-16 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0010_complaint_resolution_deadline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='investigationfinding',
            name='clarification_questions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investigationfinding',
            name='needs_faculty_statement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investigationfinding',
            name='needs_student_clarification',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ClarificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('Student', 'Student Clarification'), ('Faculty', 'Faculty Statement')], max_length=10)),
                ('questions', models.TextField(help_text='Specific questions or information needed')),
                ('status', models.CharField(choices=[('Pending', 'Pending Response'), ('Responded', 'Responded')], default='Pending', max_length=10)),
                ('response_text', models.TextField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clarification_requests', to='complaints.investigationfinding')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clarifications_requested', to=settings.AUTH_USER_MODEL)),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clarifications_responded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
