# Generated by Django 6.0.3 on 2026-05-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0010_complaint_resolution_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_type',
            field=models.CharField(choices=[('Faculty', 'Complaint about Faculty'), ('HOD', 'Complaint about HOD'), ('Staff', 'Complaint about Staff'), ('Facility', 'Facility Issue'), ('Suggestion', 'Suggestion')], max_length=20),
        ),
    ]
