# Generated by Django 6.0.3 on 2026-05-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0011_alter_complaint_complaint_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Review'), ('Reviewed', 'Reviewed'), ('Under Investigation', 'Under Investigation'), ('Findings Submitted', 'Findings Submitted'), ('Resolved', 'Resolved'), ('Escalated', 'Escalated to Higher Authority')], default='Pending', max_length=30),
        ),
    ]
