# Generated by Django 6.0.3 on 2026-05-16 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0011_investigationfinding_clarification_questions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clarificationrequest',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clarification_requests_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clarificationrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Response'), ('Responded', 'Responded'), ('Forwarded', 'Forwarded to Investigator')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='investigationfinding',
            name='clarification_questions',
            field=models.TextField(blank=True, help_text='Specific questions the investigator needs answered', null=True),
        ),
    ]
