# Generated by Django 6.0.3 on 2026-05-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0012_clarificationrequest_target_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_type',
            field=models.CharField(choices=[('Faculty', 'Complaint about Faculty'), ('HOD', 'Complaint about HOD'), ('Staff', 'Complaint about Staff'), ('Facility', 'Facility Issue'), ('Advice', 'General Advice'), ('Opinion', 'Suggestion')], max_length=20),
        ),
    ]
